# minimal from https://github.com/pages-themes/minimal
# title: 
#   Miao Cheng 
#   Tohoku University
# email: cheng*tohoku.ac.jp (replace * with at)
# description: > # Write your awesome description here
#   Miao Cheng, assistant professor @Tohoku University.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://miaocheng-org.github.io" # the base hostname & protocol for your site
# remote_theme: pages-themes/minimal@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

# minima from https://github.com/jekyll/minima
theme: minima
remote_theme: "jekyll/minima@1e8a445"
plugins:
 - jekyll-feed
 - jekyll-seo-tag

title: 
  Miao Cheng 
  Tohoku University
  
