# minimal from https://github.com/pages-themes/minimal
# title: 
#   Miao Cheng 
#   Tohoku University
# email: cheng*tohoku.ac.jp (replace * with at)
# description: > # Write your awesome description here
#   Miao Cheng, assistant professor @Tohoku University.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://miaocheng-org.github.io" # the base hostname & protocol for your site
# remote_theme: pages-themes/minimal@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

# # minima from https://github.com/jekyll/minima
# 1. Activate the Minima Theme
theme: minima

# 2. Add Site-wide settings (required by many themes/plugins)
title: Miao Cheng, Tohoku University
author:
  name: Miao Cheng
  email: cheng*tohoku.ac.jp
description: >
  Write a brief description of your site here.

# 3. Minima-specific settings (required to resolve the SASS error)
minima:
  skin: auto # Or 'classic', 'dark', 'light', etc.
  
  # 4. To resolve the SASS error, we explicitly define the brand color as a static SASS color
  #    instead of the incompatible CSS variable (var(--minima-brand-color)).
colors:
    brand: '#007ACC' # Example color: a nice blue. Choose any hex code you like.

header_pages:
  - about.md
  - Research.md
  
